---
title: "Wigan Grassland Restoration"
author: "Kaydee S. Barker"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

# Set up

```{r setup, include=FALSE}

rm(list=ls()) #clear global environment/workspace
knitr::opts_chunk$set(echo = TRUE) #default display code in knit output (FALSE will hide)

```

## Load libraries (and install if needed)

```{r libraries, warning=FALSE, include=FALSE}

#Create groups of packages/libraries 

##1. For data reading and manipulation - could just do tidyverse and a few others, or make group of specific libraries for faster loading
datalib <- c("dplyr", "tidyr", "readr", "readxl", "stringr", "tibble", "reshape2", "janitor") 

##2. For data visualization (note ggplot2 is in tidyverse)
vislib <- c("ggplot2", "ggthemes", "ggfortify", "ggrepel", "plotrix", "RColorBrewer", "Cairo", "ggsci")

##3. For calculation and stats functions, including ecology-specific libraries
statlib <- c("car", "MASS", "rcompanion", "zoo", "lme4", "MuMIn", "emmeans", "ARTool", "dunn.test", "performance", "see", "corrplot", "BAT", "vegan")

#Install packages as needed - commented out, but remove # and adjust as needed
##as a group:
#lapply(c(datalib, vislib, statlib), install.packages, character.only = TRUE)

##or individually:
#install.packages("janitor") #install janitor to help clean up data

#Load libraries
lapply(c(datalib, vislib, statlib), library, character.only = TRUE)

```

## Define custom design settings for plots

```{r design, echo=FALSE}

#Color palettes

#color palette example using hex codes
colors <- c("#84B699", "#EF8E45", "#BF876E", "#5DDEE7")

#color palette with gradient with 20 steps
colors_ramp <- colorRampPalette(c("#84B699", "azure","#BF876E"))(20)

#Color variables

#define individual colors for plot elements
plotline_color <- "#BF876E" #define color for plot lines
fill_color <- "#84B699" #define color for fill

#Custom ggplot configurations 

#Create a custom theme for ggplot with font, legend, and background settings. Transparent allows transparent png or pdf export.
my_theme <- theme(text = element_text(#family = "Arial", 
                                      size = 12, color = "grey10"), #set universal font family, size, and color
              plot.title = element_text(size = 20, color = "black", face="bold"), #set title size, color, bold
              plot.title.position = "plot", #set title position
              legend.title = element_blank(), #remove legend title
              legend.position="right", legend.box = "vertical", #where legend appears, what orientation
              panel.background = element_rect(fill='transparent'), plot.background = element_rect(fill='transparent', color=NA), #make backgrounds transparent
              panel.grid.major = element_blank(), panel.grid.minor = element_blank()) #no gridlines

```

## Order variables

```{r labels, echo=FALSE}

#Create an order of observations within a variable to override the default order for plots
order_sites <- c("Bickershaw 1", "Bickershaw 2", "Amberswood", "Flashes")

order_management <- c("Unmanaged", "4 Years", "15 Years", "23 Years")

```

## Load data

```{r load data, include=FALSE}

#read in FTIR data
FTIR <- read_csv("FTIR_Sam.csv")
FTIR$Site <- as.factor(FTIR$Site)
FTIR <- FTIR[,-1]

#standardize
FTIR_standardized <- FTIR %>%
  mutate_if(is.numeric,scale)

#numeric values only for prcomp
FTIR_standardized_num <- FTIR_standardized[,-1]

#read in field soil C/N data
SOM_fielddata <- read_csv("SOM_field.csv") 

#Combine SOM, POM, and MAOM as one observation per plot
SOM <- SOM_fielddata %>%
  filter(Fraction == "SOM") %>%
  rename("SOM_C" = "C_gkg") %>%
  rename("SOM_N" = "N_gkg") %>%
  rename("SOM_CN" = "C_N")

POM <- SOM_fielddata %>%
  filter(Fraction == "POM") %>%
  rename("POM_C" = "C_gkg") %>%
  rename("POM_N" = "N_gkg") %>%
  rename("POM_CN" = "C_N")
  
MAOM <- SOM_fielddata %>%
  filter(Fraction == "MAOM") %>%
  rename("MAOM_C" = "C_gkg") %>%
  rename("MAOM_N" = "N_gkg") %>%
  rename("MAOM_CN" = "C_N")

SOM_fielddata2 <- merge(SOM,POM, by=c("Site","Management", "Plot_ID"), all.y=TRUE) %>%
  merge(MAOM, by=c("Site","Management", "Plot_ID"), all.y=TRUE) %>%
  dplyr::select(Site, Management, Plot_ID, SOM_C, SOM_N, SOM_CN, POM_C, POM_N, POM_CN, MAOM_C, MAOM_N, MAOM_CN) %>%
  mutate(fMAOM_C = MAOM_C / (SOM_C + POM_C + MAOM_C)) %>% #calculate fMAOM C
  mutate(fMAOM_N = MAOM_N / (SOM_N + POM_N + MAOM_N)) %>% #calculate fMAOM N
  mutate(years =
           case_when(Management == "Unmanaged" ~ 0,
                     Management == "4 Years" ~ 4,
                     Management == "15 Years" ~ 15,
                     Management == "23 Years" ~ 23))

#summarize SOM data for plots
summary_SOM <- SOM_fielddata2 %>%
  dplyr::select(Site, Management, years, SOM_C, SOM_N, SOM_CN, POM_C, POM_N, POM_CN, MAOM_C, MAOM_N, MAOM_CN) %>%
  group_by(Site, Management, years) %>%
  summarise_all(funs(mean(., na.rm=TRUE), sd(., na.rm=TRUE), std.error(., na.rm=TRUE)))

#read in AM data
AMdata <- read_csv("Wigan_myc.csv")

#read in respiration data
resp <- read_csv("Wigan_respiration.csv")

#read in 13C initial harvest data
harvest <- read_csv("Stagg_harvest.csv") %>% #load
  clean_names() #clean up column names

#pivot and calculate root:shoot ratio
plant_harvest <- harvest %>%
  mutate(across(c(6:15), as.numeric)) %>% #convert columns to numeric
  dplyr::select(site, management, pot, species, sample_type, biomass_g) %>%
  filter(biomass_g >= 0) %>% #remove non-plant data
  group_by(site, management, pot, species, sample_type) %>%
  summarise(biomass_g = mean(biomass_g, na.rm = TRUE), .groups = 'drop') %>% #summarize duplicate entries for groups
  pivot_wider(names_from = sample_type, values_from = biomass_g) %>% #determines observation name and value columns
  mutate(root_shoot = #calculate root:shoot ratio
           dplyr::case_when(root > 0 & shoot > 0 ~ root / shoot, #when values are present
                     TRUE ~ NA)) %>% #default to NA when values are not present
  mutate(harvesttime = #define harvest time
        case_when(pot == "G1" | pot == "G20" | pot == "G30" | pot == "G31" | pot == "G39" |
                  pot == "G8" | pot == "G33" | pot == "G35" | pot == "G41" | pot == "G42" |
                  pot == "G9" | pot == "G12" | pot == "G22" | pot == "GA1" | pot == "GA2" |
                  pot == "G11" | pot == "G18" | pot == "G29" | pot == "GF1" | pot == "GX"
                  ~ "T0", #time 0 beginning of incubation
                     TRUE ~ "T10mos")) #10 months incubation

#summarize by plant species
summary_species <- plant_harvest %>%
  dplyr::select(species, shoot, root, root_shoot) %>%
  group_by(species) %>%
  summarise_all(funs(mean(., na.rm=TRUE), sd(., na.rm=TRUE), std.error(., na.rm=TRUE)))

#add mean data to harvest data for estimates
plant_harvest_est <- plant_harvest %>%
  #replace(is.na(.), 0) %>%
  mutate(site2 =
           case_when(pot == "G20" | pot == "G31" | #higher root values
                       pot == "G37" | pot == "G7"
                     ~ "bickershaw1_high",
                     pot == "G1" | pot == "G30" | pot == "G39" | #lower root values
                       pot == "G34" | pot == "G26" | pot == "G3" 
                     ~ "bickershaw1_low",
                     pot == "G33" | pot == "G35" | pot == "G41" |
                       pot == "G23" | pot == "G24" |pot == "G40"
                     ~ "bickershaw2_high",
                     pot == "G8" | pot == "G42" |
                       pot == "G4" | pot == "G28"
                     ~ "bickershaw2_low",
                     pot == "G12" | pot == "GA1" | pot == "GA2" |
                       pot == "G5" | pot == "G6" | pot == "GA4" 
                     ~ "amberswood_high",
                     pot == "G22" | pot == "G9" |
                       pot == "G21" | pot == "GA3"
                     ~ "amberswood_low",
                     .default = site)) %>%
  mutate(root_shoot =
           case_when(root_shoot > 0 ~ root_shoot, 
                     TRUE ~ summary_species$root_shoot_mean
                     [match(species, summary_species$species)])) %>%
  mutate(root =
           case_when(root > 0 ~ root,
                     TRUE ~ root_shoot * shoot))

#summarize general roots amount by site
general_roots <- plant_harvest_est %>%
  filter(species == "general_roots") %>%
  dplyr::select(site2, root) %>%
  group_by(site2) %>%
  summarise_all(funs(mean(., na.rm=TRUE), sd(., na.rm=TRUE), std.error(., na.rm=TRUE)))

#calculate and estimate biomass per pot
total_pots <- plant_harvest_est %>%
  dplyr::select(site2, management, pot, harvesttime, root, shoot, root_shoot) %>%
  group_by(site2, management, pot, harvesttime) %>%
  summarise(root = sum(root, na.rm=TRUE), shoot = sum(shoot, na.rm=TRUE), root_shoot = mean(root_shoot, na.rm=TRUE)) %>% #summarize
  mutate(root = #add some general roots to the estimated beginning biomass for incubation
           dplyr::case_when(harvesttime == "T0" ~ root,
                     TRUE ~ root + general_roots$mean[match(site2, general_roots$site2)])) #+
                     #general_roots$sd[match(site2, general_roots$site2)]))

#write csv for measured and estimated beginning biomass
write.csv(plant_harvest_est, "begin_estimates_bysp.csv") #saves as csv in current workspace
write.csv(total_pots, "begin_estimates_bypot.csv") #saves as csv in current workspace

#read in incubation data, add beginning, calculate change in biomass
endbiomass <- read_csv("End_incubation_biomass.csv") %>% #load
  mutate(est_beg_drymass = total_pots$root[match(Pot, total_pots$pot)]) %>% #add estimated beginning biomass
  mutate(beg_drymass_perL = est_beg_drymass / 6.1) %>% #calculate dry mass per liter
  mutate(dmass_dT = est_beg_drymass - end_drymass_clean) %>% #calculate change in dry mass
  mutate(dmass_dT_perL = beg_drymass_perL - end_drymass_perL_clean) %>% #calculate change in dry mass per liter
  mutate(decomp_per_unadj = dmass_dT / est_beg_drymass) %>% #calculate decomposition percentage - not adjusting volume
  mutate(decomp_per_adj = dmass_dT_perL / beg_drymass_perL) %>% #calculate decomposition percentage - adjusting volume
  mutate(years =
           case_when(Management == "Unmanaged" ~ 0,
                     Management == "4 Years" ~ 4,
                     Management == "15 Years" ~ 15,
                     Management == "23 Years" ~ 23))

#summarise
summary_endbio <- endbiomass %>%
  dplyr::select(Management, years, rocks_debris, end_drymass_clean, end_drymass_perL_clean, est_beg_drymass, beg_drymass_perL, decomp_per_adj) %>%
  group_by(Management, years) %>%
  summarise_all(funs(mean(., na.rm=TRUE), sd(., na.rm=TRUE), std.error(., na.rm=TRUE)))

#order variables for each
SOM_fielddata2$Site <- factor(SOM_fielddata2$Site, levels = order_sites)
endbiomass$Management <- factor(endbiomass$Management, levels = order_management)
summary_endbio$Management <- factor(summary_endbio$Management, levels = order_management)

```


# PCA on FTIR Data

```{r PCA}

#PCA
FTIR_pca <- prcomp(FTIR_standardized_num) #perform PCA on standardized variables

summary(FTIR_pca) #view importance of principal components and proportion of variances

FTIR_pca$rotation #view loadings from the standardized data
screeplot(FTIR_pca) # diagnostic plot to make sure principal components are in order

#basic plot
biplot(FTIR_pca)

#customized plot
autoplot(FTIR_pca, data = FTIR_standardized, colour = 'Site', 
        loadings = TRUE, loadings.colour = 'red',
        loadings.label = TRUE, loadings.label.size = 3,
        frame = TRUE, frame.type = 'norm') +
  theme_bw() + 
  ggtitle("Principal Components of FTIR Wavelengths Across Sites") 

```

# Field Soil C and N Analyses

## Charts

```{r SOC}

summary_SOM$Site <- factor(summary_SOM$Site, levels = order_sites)
summary_SOM$Management <- factor(summary_SOM$Management, levels = order_management)

#SOM C bar chart with error bars
ggplot(data = summary_SOM, aes(x=Site, y=SOM_C_mean, fill=Site)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=SOM_C_mean-SOM_C_std.error, ymax=SOM_C_mean+SOM_C_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Soil Organic Matter C per site") + #add a graph title
  xlab("Site") + ylab("C (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('SOC.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r SOM-N}

#SOM N bar chart with error bars
ggplot(data = summary_SOM, aes(x=Site, y=SOM_N_mean, fill=Site)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=SOM_N_mean-SOM_N_std.error, ymax=SOM_N_mean+SOM_N_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Soil Organic Matter N per site") + #add a graph title
  xlab("Site") + ylab("N (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('SOM_N.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r SOM-CN}

#SOM CN boxplot
ggplot(data = SOM_fielddata2) + 
	geom_boxplot(aes(x=Site, y=SOM_CN, fill=Site)) +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Soil Organic Matter C:N per site") + #add a graph title
  xlab("Site") + ylab("C:N") + #define/change X and Y labels
  my_theme

#save figure
ggsave('SOM_CN.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r combined C plots}

SOM_fielddata$Site <- factor(SOM_fielddata$Site, levels = order_sites)
SOM_fielddata$Management <- factor(SOM_fielddata$Management, levels = order_management)

#combined boxplots with error bars
ggplot(data = SOM_fielddata) + 
	geom_boxplot(aes(x=Management, y=C_gkg, fill=Fraction)) +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Soil Organic Matter C per site") + #add a graph title
  xlab("Site") + ylab("C (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('SOMC_all.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r combined N plots}

#combined boxplots with error bars
ggplot(data = SOM_fielddata) + 
	geom_boxplot(aes(x=Site, y=N_gkg, fill=Fraction)) +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Soil Organic Matter N per site") + #add a graph title
  xlab("Site") + ylab("N (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('SOM_N_all.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r combined CN}

#SOM CN boxplot
ggplot(data = SOM_fielddata) + 
	geom_boxplot(aes(x=Site, y=C_N, fill=Fraction)) +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Soil Organic Matter C:N per site") + #add a graph title
  xlab("Site") + ylab("C:N") + #define/change X and Y labels
  my_theme

```

```{r POM-C}

#POM C bar chart with error bars
ggplot(data = summary_SOM, aes(x=Site, y=POM_C_mean, fill=Site)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=POM_C_mean-POM_C_std.error, ymax=POM_C_mean+POM_C_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Particulate Organic Matter C per site") + #add a graph title
  xlab("Site") + ylab("C (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('POM_Cbar.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r POM-N}

#POM N bar chart with error bars
ggplot(data = summary_SOM, aes(x=Site, y=POM_N_mean, fill=Site)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=POM_N_mean-POM_N_std.error, ymax=POM_N_mean+POM_N_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Particulate Organic Matter N per site") + #add a graph title
  xlab("Site") + ylab("N (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('POM_Nbar.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r MAOM-C}

#MAOM C bar chart with error bars
ggplot(data = summary_SOM, aes(x=Site, y=MAOM_C_mean, fill=Site)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=MAOM_C_mean-MAOM_C_std.error, ymax=MAOM_C_mean+MAOM_C_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Mineral Associated Organic Matter C per site") + #add a graph title
  xlab("Site") + ylab("C (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('MAOM_Cbar.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r MAOM-N}

#MAOM N bar chart with error bars
ggplot(data = summary_SOM, aes(x=Site, y=MAOM_N_mean, fill=Site)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=MAOM_N_mean-MAOM_N_std.error, ymax=MAOM_N_mean+MAOM_N_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Mineral Associated Organic Matter N per site") + #add a graph title
  xlab("Site") + ylab("N (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('MAOM_Nbar.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r fMAOM-C}

#fMAOM C box chart
ggplot(data = SOM_fielddata2, aes(x=Site, y=fMAOM_C, fill=Site)) + 
	geom_boxplot() +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("fMAOM C per site") + #add a graph title
  xlab("Site") + ylab("C (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('fMAOM_C.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

```{r fMAOM-N}

#fMAOM N box chart
ggplot(data = SOM_fielddata2, aes(x=Site, y=fMAOM_N, fill=Site)) + 
	geom_boxplot() +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("fMAOM N per site") + #add a graph title
  xlab("Site") + ylab("N (g/kg)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('fMAOM_N.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

```

## SOM Stats
```{r SOM field stats}
shapiro.test(resid(lm(SOM_C ~ Management, data = SOM_fielddata2))) #check normality of residuals - normal
summary(aov(SOM_C ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(SOM_C ~ Management, data = SOM_fielddata2)) 

shapiro.test(resid(lm(SOM_N ~ Management, data = SOM_fielddata2))) #normal
summary(aov(SOM_N ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(SOM_N ~ Management, data = SOM_fielddata2))

shapiro.test(resid(lm(POM_C ~ Management, data = SOM_fielddata2))) #not normal
shapiro.test(resid(lm(log(POM_C) ~ Management, data = SOM_fielddata2))) #normal
summary(aov(log(POM_C) ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(log(POM_C) ~ Management, data = SOM_fielddata2))

shapiro.test(resid(lm(POM_N ~ Management, data = SOM_fielddata2))) #normal
summary(aov(POM_N ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(POM_N ~ Management, data = SOM_fielddata2))

shapiro.test(resid(lm(MAOM_C ~ Management, data = SOM_fielddata2))) #normal
summary(aov(MAOM_C ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(MAOM_C ~ Management, data = SOM_fielddata2))

shapiro.test(resid(lm(MAOM_N ~ Management, data = SOM_fielddata2))) #normal
summary(aov(MAOM_N ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(MAOM_N ~ Management, data = SOM_fielddata2))

shapiro.test(resid(lm(fMAOM_C ~ Management, data = SOM_fielddata2))) #normal
summary(aov(fMAOM_C ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(fMAOM_C ~ Management, data = SOM_fielddata2))

shapiro.test(resid(lm(fMAOM_N ~ Management, data = SOM_fielddata2))) #normal
summary(aov(fMAOM_N ~ Management, data = SOM_fielddata2))
TukeyHSD(aov(fMAOM_N ~ Management, data = SOM_fielddata2))

```

# AM Association

```{r AM}

AMdata$Management <- factor(AMdata$Management, levels = order_management)

#Hyphal presence boxplot
ggplot(data = AMdata, aes(x=Management, y=hyph_percent, fill=Management)) + 
	geom_boxplot() + 
  scale_fill_manual(values = colors) + #define colors to use
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + #change to %
  my_theme +
  #ggtitle("Hyphal Presence Across Sites") + #add a graph title
  xlab("Management") + ylab("Hyphal Presence (% of Root)") #define/change X and Y labels

ggsave('AM_hyph.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
       path = "Figures", #save to folder
       width = 6, height = 4, units = "in", #set dimensions
       dpi = 300, #set resolution
       bg=NULL) #background from plot specifications

shapiro.test(resid(lm(hyph_percent ~ Management, data = AMdata))) #check normality of residuals - normal
summary(aov(hyph_percent ~ Management, data = AMdata)) #P=0.00027
TukeyHSD(aov(hyph_percent ~ Management, data = AMdata)) #23 vs. 0 P=0.0034, vs. 4 0.0007, 15 vs. 4 0.023


```

# Incubation Results

## Respiration Data

### 12 C

```{r resp overall 12}

resp$Management <- factor(resp$Management, levels = order_management)

ggplot(data = resp, aes(x=Management, y=CO2_ppm, fill=Management)) + 
	geom_boxplot() + 
  scale_fill_manual(values = colors) + #define colors to use
  my_theme +
  ggtitle("12CO2 Respiration") + #add a graph title
  xlab("Management") + ylab("CO2 (ppm)") #define/change X and Y labels

ggsave('CO2_overall.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
       path = "Figures", #save to folder
       width = 6, height = 4, units = "in", #set dimensions
       dpi = 300, #set resolution
       bg=NULL) #background from plot specifications

#ANOVA and Tukey
CO2 <- aov(CO2_ppm ~ factor(Management), data = resp)
summary(CO2) #P=0.1
TukeyHSD(CO2) #none - unmanaged vs 15 almost

```

```{r resp 12C by week}

#time series boxplots of 12C
ggplot(data = resp, aes(x=Week, y=CO2_ppm, group=interaction(Week,Management))) + 
  geom_boxplot(aes(fill=Management), position = position_dodge()) +
  geom_dotplot(aes(fill=Management, stroke=TRUE), binaxis = "y", dotsize = 0.5, position = position_dodge(), stackdir = "center", binpositions = "bygroup") +
  scale_fill_manual(values = colors) + #define colors to use
  scale_color_manual(values = colors) +
  my_theme +
  scale_y_continuous(name="12CO2 (ppm)", breaks = pretty(c(600,3200), n = 8)) + #set limits and change number of tick marks on y axis
  scale_x_continuous(name ="Weeks of Incubation", breaks = c(0,1,2,3,4)) #set ticks and label for x axis

ggsave('12C_wks.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
       path = "Figures", #save to folder
       width = 7, height = 4, units = "in", #set dimensions
       dpi = 300, #set resolution
       bg=NULL) #background from plot specifications


```

### 13 C

```{r resp overall 13}

ggplot(data = resp, aes(x=Management, y=d13CO2_permille, fill=Management)) + 
	geom_boxplot() + 
  scale_fill_manual(values = colors) + #define colors to use
  my_theme +
  ggtitle("13CO2 Respiration") + #add a graph title
  xlab("Management") + ylab("Delta 13CO2 (per mille)") + #define/change X and Y labels
  theme(legend.position='none') #remove legend

ggsave('13CO2_overall.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
       path = "Figures", #save to folder
       width = 6, height = 4, units = "in", #set dimensions
       dpi = 300, #set resolution
       bg=NULL) #background from plot specifications

#ANOVA and Tukey
D13C <- aov(d13CO2_permille ~ factor(Management), data = resp)
summary(D13C) #P=0.0011
TukeyHSD(D13C) #23 vs. 15 0.00058, vs. unmanaged 0.074, 15 vs. 4 0.033

```

```{r resp 13C by week}

#time series boxplots of 12C
ggplot(data = resp, aes(x=Week, y=d13CO2_permille, group=interaction(Week,Management))) + 
  geom_boxplot(aes(fill=Management), position = position_dodge()) +
  geom_dotplot(aes(fill=Management, stroke=TRUE), binaxis = "y", dotsize = 0.5, position = position_dodge(), stackdir = "center", binpositions = "bygroup") +
  scale_fill_manual(values = colors) + #define colors to use
  scale_color_manual(values = colors) +
  my_theme +
  scale_y_continuous(name="Delta 13CO2 (per mille)", breaks = pretty(c(600,3200), n = 8)) + #set limits and change number of tick marks on y axis
  scale_x_continuous(name ="Weeks of Incubation", breaks = c(0,1,2,3,4)) #set ticks and label for x axis

ggsave('13C_wks.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
       path = "Figures", #save to folder
       width = 7, height = 4, units = "in", #set dimensions
       dpi = 300, #set resolution
       bg=NULL) #background from plot specifications


```

## Root:shoot ratio
```{r rs, warning=FALSE}

#root:shoot ratio box plot
ggplot(data = plant_harvest_est[-c(118,153),], #species data minus major outliers
       aes(x=management, y=root_shoot, fill=management)) + 
	geom_boxplot() +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Root:Shoot ratio per management time") + #add a graph title
  xlab("Management") + ylab("Root:Shoot ratio") + #define/change X and Y labels
  my_theme

```

## Biomass

### Beginning combined roots
```{r beg root bio, warning=FALSE}

#mass bar chart with error bars
ggplot(data = summary_endbio, aes(x=Management, y=est_beg_drymass_mean, fill=Management)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=est_beg_drymass_mean-est_beg_drymass_std.error, ymax=est_beg_drymass_mean+est_beg_drymass_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Beginning biomass per management time") + #add a graph title
  xlab("Management") + ylab("Root dry mass (g)") + #define/change X and Y labels
  my_theme

#ANOVA and Tukey
begmass_aov <- aov(est_beg_drymass ~ factor(Management), data = endbiomass)
summary(begmass_aov) #P=0.00027
TukeyHSD(begmass_aov) #Unmanaged-23 Years P=0.0048, 4 Years-23 Years P=0.00067, 15 Years-23 Years P=0.00053

```

### Ending combined roots
```{r end root bio, warning=FALSE}

#mass bar chart with error bars
ggplot(data = summary_endbio, aes(x=Management, y=end_drymass_clean_mean, fill=Management)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=end_drymass_clean_mean-end_drymass_clean_std.error, ymax=end_drymass_clean_mean+end_drymass_clean_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Ending biomass per management time") + #add a graph title
  xlab("Management") + ylab("Root dry mass (g)") + #define/change X and Y labels
  my_theme

#ANOVA and Tukey
endmass_aov <- aov(end_drymass_clean ~ factor(Management), data = endbiomass)
summary(endmass_aov) #P=0.0268
TukeyHSD(endmass_aov) #Unmanaged-23yr P=0.024, 4yr-23yr almost 0.077

```

### Decomposition

```{r decomp, warning=FALSE}

#decomposition percentage box plot
ggplot(data = endbiomass, aes(x=Management, y=decomp_per_adj)) + 
	geom_boxplot(aes(fill=Management)) +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Decomposition per Management") + #add a graph title
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + #change to %
  xlab("Management") + ylab("Decomposition (%)") + #define/change X and Y labels
  my_theme

#decomposition lm plot
ggplot(data = endbiomass[-1,], aes(x=years, y=decomp_per_adj)) + 
	geom_point(aes(color=Management), size=2, alpha=0.5) +
  scale_fill_manual(values=colors) + #define colors to use
  geom_smooth(method="lm", se=TRUE, color=plotline_color, fill=fill_color) +
  scale_x_continuous(breaks=c(0,4,15,23), expand = c(0.1,0.1)) + #set limits and change tick marks on x axis
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + #change to %
  ggtitle("Decomposition by Restoration Time") + #add a graph title
  xlab("Management Time") + ylab("Decomposition (%)") + #define/change X and Y labels
  my_theme

#save figure
ggsave('decomp.svg', #save plot name and type - can be "eps", "pdf", "jpeg", "tiff", "png", "bmp", "svg"
	path = "Figures", #save to folder within working directory
	width = 6, height = 4, units = "in", #set dimensions for figure
	dpi = 300, #set resolution
	bg=NULL) #background from plot specifications

#ANOVA and Tukey
decomp_aov <- aov(decomp_per_adj ~ factor(Management), data = endbiomass[-1,]) #remove G37
summary(decomp_aov) #P=0.0012
TukeyHSD(decomp_aov) #23yr vs. unmanaged P=0.0021, 23yr vs 4yr 0.013, 15yr vs unmanaged almost 0.057
kruskal.test(decomp_per_adj ~ factor(Management), data = endbiomass[-1,]) #Kruskal-Wallis rank sum test P=0.0089
dunn.test(endbiomass[-1,]$decomp_per_adj, endbiomass[-1,]$Management, method="bonferroni", kw=TRUE) #KW P=0.01, 23yr vs. unmanaged P=0.0053, 23yr vs. 4yr 0.047



```

## Rocks and debris

```{r rocks, warning=FALSE}

#mass bar chart with error bars
ggplot(data = summary_endbio, aes(x=Management, y=rocks_debris_mean, fill=Management)) + 
	geom_bar(stat = "identity", width = 0.7, position = "dodge") +
  scale_fill_manual(values=colors) + #define colors to use
  geom_errorbar(aes(ymin=rocks_debris_mean-rocks_debris_std.error, ymax=rocks_debris_mean+rocks_debris_std.error),
  color = "grey10", width = 0.7, position = "dodge") + 
  ggtitle("Rocks and Debris per site") + #add a graph title
  xlab("Management") + ylab("Mass (g)") + #define/change X and Y labels
  my_theme

#ANOVA and Tukey
rmass_aov <- aov(rocks_debris ~ factor(Management), data = endbiomass)
summary(rmass_aov) #P=2.3e-6
TukeyHSD(rmass_aov) #Unmanaged-23 yr P=0.0000012, Unmanaged-15 yr P=0.0057, 4 yr-23 yr P=0.00013, 15 yr-23 yr P=0.0013

```

## Worms

```{r worms, warning=FALSE}

#worms box plot
ggplot(data = endbiomass, aes(x=Management, y=worms, fill=Management)) + 
	geom_boxplot() +
  scale_fill_manual(values=colors) + #define colors to use
  ggtitle("Worms per site") + #add a graph title
  xlab("Management") + ylab("Number of worms") + #define/change X and Y labels
  my_theme

```
